### ISSUE TITLE
Support sqlalchemy 1.4

### ISSUE THREAD

**Issue by cwegrzyn** [bluelabsio/records-mover#166]
sqlalchemy 1.4 has some breaking changes. At the very least, we need to [remove all uses of `contextual_connect`](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-b922b1e71ec804bcec35652cbfdcf120) (which appears to be safe since we don't appear to use `threadlocal` anywhere).

Once sqlalchemy is supported in core records-mover, we should make sure that we only lift the restriction once all sqlalchemy packages have updated their own version constraints to account for their own support. (For example, sqlalchemy bigquery support [does not currently support 1.4](https://github.com/googleapis/python-bigquery-sqlalchemy/issues/83) but they have updated their constraints to reflect this)

**Comment by cwegrzyn** [comment]
Looks like bigquery sqlalchemy 1.4 support is close: https://github.com/googleapis/python-bigquery-sqlalchemy/pull/177

**Comment by austinweisgrau** [comment]
bigquery compatibility has been achieved since just a few days after Chris's last message above, see: https://github.com/googleapis/python-bigquery-sqlalchemy/releases/tag/v0.8.0

**Comment by ryantimjohn** [comment]
Completed in #208
