### ISSUE TITLE
Redshift table source should implement UNLOAD ... to S3

### ISSUE THREAD

**Issue by austinweisgrau** [bluelabsio/records-mover#176]
If data is being moved out of redshift, the most performative method [1] to do so is by using the UNLOAD command to unload data to S3, and then moving it around as needed from there. Extra boost when unloading as parquet versus as csv when feasible. This becomes more important the larger the data source is.

1. except for very small tables, but then the difference is trivial

**Comment by apiology** [comment]
Hi @austinweisgrau!  That support is implemented here: https://github.com/bluelabsio/records-mover/blob/master/records_mover/db/redshift/unloader.py#L50-L115

If you're not seeing it be used in a particular move, the next step would be to debug why this is.   Perhaps S3 creds and temporary bucket information weren't available.  Ideally logs will show what's going on and perhaps offer a warning - maybe that's the missing piece.

**Comment by ryantimjohn** [comment]
Going to call this resolved, feel free to reach out for follow-up Austin!
